"""
Code Executor Agent for TreeQuest Lab

Writes safe, executable ML experiment code from research proposals.
Generates Python scripts with proper error handling and logging.
"""

import ast
import logging
import os
import re
from pathlib import Path
from typing import Optional
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class ExecutionConfig(BaseModel):
    """Configuration for CodeExecutor."""
    
    template_dir: str = Field(
        default="experiments/configs",
        description="Directory containing experiment templates"
    )
    output_dir: str = Field(
        default="experiments/outputs",
        description="Directory for generated experiment scripts"
    )
    timeout_seconds: int = Field(
        default=3600,
        gt=0,
        description="Maximum execution time for experiments"
    )
    max_file_size_kb: int = Field(
        default=1024,
        gt=0,
        description="Maximum generated file size"
    )
    allowed_imports: list[str] = Field(
        default_factory=lambda: [
            "torch", "transformers", "datasets", "numpy", "pandas",
            "matplotlib", "seaborn", "sklearn", "tqdm", "json", "os",
            "sys", "logging", "time", "random", "pathlib", "typing",
            "dataclasses", "collections", "itertools", "functools"
        ],
        description="Whitelist of allowed imports"
    )
    forbidden_patterns: list[str] = Field(
        default_factory=lambda: [
            r"os\.system\s*\(",
            r"subprocess\.",
            r"__import__\s*\(",
            r"exec\s*\(",
            r"eval\s*\(",
            r"open\s*\(.*['\"].*[wb].*['\"]",  # Binary file writes
            r"socket\.",
            r"urllib\.",
            r"requests\.",
        ],
        description="Regex patterns to forbid in generated code"
    )
    
    class Config:
        extra = "ignore"


class GeneratedCode(BaseModel):
    """Container for generated experiment code."""
    
    hypothesis: str = Field(..., description="The hypothesis this code tests")
    code: str = Field(..., description="The generated Python code")
    dependencies: list[str] = Field(default_factory=list, description="Required packages")
    estimated_runtime: str = Field(..., description="Estimated runtime")
    input_requirements: list[str] = Field(default_factory=list, description="Required inputs/data")
    output_files: list[str] = Field(default_factory=list, description="Expected output files")
    
    def save(self, filepath: Path | str) -> Path:
        """Save code to file."""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        filepath.write_text(self.code)
        logger.info(f"Saved generated code to {filepath}")
        return filepath
    
    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return self.model_dump()


class CodeExecutor:
    """
    Agent that generates and validates ML experiment code.
    
    Transforms research proposals into executable Python scripts.
    Includes safety checks and validation.
    """
    
    BASE_TEMPLATE = '''"""
Auto-generated experiment script for TreeQuest Lab.
Hypothesis: {hypothesis}

This script was generated by the CodeExecutor agent.
DO NOT EDIT MANUALLY - changes will be overwritten.
"""

import logging
import json
import os
import sys
from pathlib import Path
from typing import Any
from dataclasses import dataclass, asdict

import numpy as np
import torch
from tqdm import tqdm

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Ensure reproducibility
SEED = {seed}
np.random.seed(SEED)
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

@dataclass
class ExperimentConfig:
    """Experiment configuration."""
    seed: int = SEED
    device: str = "cuda" if torch.cuda.is_available() else "cpu"
    output_dir: str = "{output_dir}"
    
    # Model config
    model_name: str = "{model_name}"
    hidden_size: int = 128
    num_layers: int = 4
    
    # Training config
    learning_rate: float = 1e-4
    batch_size: int = 32
    num_epochs: int = 5
    warmup_steps: int = 100
    
    # Evaluation config
    eval_steps: int = 50
    log_steps: int = 10
    
    def __post_init__(self):
        Path(self.output_dir).mkdir(parents=True, exist_ok=True)
    
    def save(self, path: str | Path):
        """Save config to JSON."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=2)
        logger.info(f"Saved config to {{path}}")
    
    @classmethod
    def load(cls, path: str | Path) -> "ExperimentConfig":
        """Load config from JSON."""
        with open(path) as f:
            data = json.load(f)
        return cls(**data)


class ExperimentRunner:
    """Main experiment runner."""
    
    def __init__(self, config: ExperimentConfig):
        self.config = config
        self.device = torch.device(config.device)
        self.results = {{}}
        
    def setup(self) -> None:
        """Initialize experiment components."""
        logger.info(f"Setting up experiment on {{self.device}}")
        # TODO: Initialize model, data loaders, optimizer
        
    def train_epoch(self, epoch: int) -> dict[str, float]:
        """Run one training epoch."""
        # TODO: Implement training loop
        losses = []
        for step in range(10):  # Placeholder
            # Simulated training step
            loss = np.random.uniform(0.5, 2.0) * (1.0 - epoch / self.config.num_epochs)
            losses.append(loss)
            
            if step % self.config.log_steps == 0:
                logger.info(f"Epoch {{epoch}}, Step {{step}}, Loss: {{loss:.4f}}")
        
        return {{"train_loss": np.mean(losses)}}
    
    def evaluate(self) -> dict[str, float]:
        """Run evaluation."""
        # TODO: Implement evaluation
        metrics = {{
            "val_loss": np.random.uniform(0.3, 1.5),
            "accuracy": np.random.uniform(0.6, 0.9),
        }}
        logger.info(f"Evaluation metrics: {{metrics}}")
        return metrics
    
    def run(self) -> dict[str, Any]:
        """Run full experiment."""
        logger.info("Starting experiment")
        self.setup()
        
        all_metrics = []
        for epoch in range(self.config.num_epochs):
            train_metrics = self.train_epoch(epoch)
            
            if epoch % self.config.eval_steps == 0 or epoch == self.config.num_epochs - 1:
                eval_metrics = self.evaluate()
                epoch_metrics = {{**train_metrics, **eval_metrics, "epoch": epoch}}
                all_metrics.append(epoch_metrics)
                
                # Save checkpoint
                checkpoint_path = Path(self.config.output_dir) / f"checkpoint_epoch_{{epoch}}.pt"
                # torch.save({{"epoch": epoch, "metrics": epoch_metrics}}, checkpoint_path)
        
        # Final evaluation
        final_metrics = self.evaluate()
        self.results = {{
            "config": asdict(self.config),
            "epochs": len(all_metrics),
            "metrics_history": all_metrics,
            "final_metrics": final_metrics,
        }}
        
        # Save results
        results_path = Path(self.config.output_dir) / "results.json"
        with open(results_path, "w") as f:
            json.dump(self.results, f, indent=2)
        logger.info(f"Saved results to {{results_path}}")
        
        return self.results


def main():
    """Main entry point."""
    config = ExperimentConfig()
    config.save(Path(config.output_dir) / "config.json")
    
    runner = ExperimentRunner(config)
    results = runner.run()
    
    print("\\n" + "=" * 60)
    print("EXPERIMENT COMPLETE")
    print("=" * 60)
    print(f"Final metrics: {{results['final_metrics']}}")
    print(f"Results saved to: {{config.output_dir}}")
    
    return results


if __name__ == "__main__":
    main()
'''

    def __init__(self, config: Optional[ExecutionConfig] = None):
        self.config = config or ExecutionConfig()
        self._generation_count = 0
        
        # Create directories
        Path(self.config.output_dir).mkdir(parents=True, exist_ok=True)
    
    def generate_code(
        self,
        hypothesis: str,
        method_summary: list[str],
        domain: str = "ml",
        seed: int = 42
    ) -> GeneratedCode:
        """
        Generate experiment code from a research proposal.
        
        Args:
            hypothesis: The hypothesis to test
            method_summary: List of method steps from proposal
            domain: Research domain
            seed: Random seed
            
        Returns:
            GeneratedCode object
        """
        self._generation_count += 1
        
        # Extract key parameters from hypothesis/method
        params = self._extract_parameters(hypothesis, method_summary)
        
        # Generate code using template
        code = self.BASE_TEMPLATE.format(
            hypothesis=hypothesis,
            seed=seed,
            output_dir=f"{self.config.output_dir}/exp_{self._generation_count}",
            model_name=params.get("model_name", "bert-base-uncased"),
        )
        
        # Add custom logic based on method
        code = self._customize_code(code, method_summary, domain)
        
        # Validate safety
        is_safe, issues = self.validate_safety(code)
        if not is_safe:
            logger.warning(f"Safety issues detected: {issues}")
            # In production, we'd regenerate or raise error
            # For now, we proceed with warnings logged
        
        # Extract dependencies
        deps = self._extract_dependencies(code)
        
        # Estimate runtime
        runtime = self._estimate_runtime(method_summary)
        
        generated = GeneratedCode(
            hypothesis=hypothesis,
            code=code,
            dependencies=deps,
            estimated_runtime=runtime,
            input_requirements=self._get_input_requirements(domain),
            output_files=["results.json", "config.json", "metrics.csv"]
        )
        
        logger.info(f"Generated code #{self._generation_count} for: {hypothesis[:50]}...")
        return generated
    
    def _extract_parameters(
        self,
        hypothesis: str,
        method_summary: list[str]
    ) -> dict[str, str]:
        """Extract relevant parameters from proposal text."""
        params = {}
        
        # Simple keyword-based extraction
        hypothesis_lower = hypothesis.lower()
        
        if "lora" in hypothesis_lower or "peft" in hypothesis_lower:
            params["model_name"] = "microsoft/phi-2"
            params["adapter"] = "lora"
        elif "checkpoint" in hypothesis_lower:
            params["gradient_checkpointing"] = "true"
        elif "counterfactual" in hypothesis_lower or "augmentation" in hypothesis_lower:
            params["task"] = "text_generation"
            params["dataset"] = "gsm8k"
        elif "learning rate" in hypothesis_lower or "lr" in hypothesis_lower:
            params["optimizer"] = "adamw"
            params["scheduler"] = "cosine"
        else:
            params["model_name"] = "prajjwal1/bert-tiny"  # Default small model
        
        return params
    
    def _customize_code(
        self,
        code: str,
        method_summary: list[str],
        domain: str
    ) -> str:
        """Customize code based on method requirements."""
        
        # Add domain-specific imports
        if "text" in domain or "language" in domain:
            if "from transformers" not in code:
                code = code.replace(
                    "import torch",
                    "import torch\nfrom transformers import AutoModel, AutoTokenizer"
                )
        
        # Add method-specific comments
        method_section = "\n# Method Implementation:\n"
        for i, step in enumerate(method_summary, 1):
            method_section += f"# {i}. {step}\n"
        
        # Insert before ExperimentRunner class
        marker = "class ExperimentRunner:"
        if marker in code:
            code = code.replace(marker, method_section + "\n" + marker)
        
        return code
    
    def validate_safety(self, code: str) -> tuple[bool, list[str]]:
        """
        Validate code safety.
        
        Returns:
            Tuple of (is_safe, list_of_issues)
        """
        issues = []
        
        # Check forbidden patterns
        for pattern in self.config.forbidden_patterns:
            matches = re.findall(pattern, code, re.IGNORECASE)
            if matches:
                issues.append(f"Forbidden pattern detected: {pattern}")
        
        # Check imports
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if alias.name not in self.config.allowed_imports:
                            issues.append(f"Non-whitelisted import: {alias.name}")
                elif isinstance(node, ast.ImportFrom):
                    if node.module and node.module.split('.')[0] not in self.config.allowed_imports:
                        issues.append(f"Non-whitelisted import from: {node.module}")
        except SyntaxError as e:
            issues.append(f"Syntax error: {e}")
            return False, issues
        
        # Check file size
        if len(code.encode('utf-8')) / 1024 > self.config.max_file_size_kb:
            issues.append(f"Code exceeds maximum size ({len(code.encode('utf-8'))/1024:.1f} KB)")
        
        return len(issues) == 0, issues
    
    def _extract_dependencies(self, code: str) -> list[str]:
        """Extract required dependencies from code."""
        deps = set()
        
        # Common package mappings
        import_map = {
            "torch": "torch",
            "transformers": "transformers",
            "datasets": "datasets",
            "numpy": "numpy",
            "pandas": "pandas",
            "matplotlib": "matplotlib",
            "sklearn": "scikit-learn",
            "tqdm": "tqdm",
        }
        
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        base = alias.name.split('.')[0]
                        if base in import_map:
                            deps.add(import_map[base])
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        base = node.module.split('.')[0]
                        if base in import_map:
                            deps.add(import_map[base])
        except SyntaxError:
            pass
        
        return sorted(list(deps))
    
    def _estimate_runtime(self, method_summary: list[str]) -> str:
        """Estimate runtime from method description."""
        method_str = " ".join(method_summary).lower()
        
        if "full fine-tuning" in method_str or "large model" in method_str:
            return "high (>4 hours)"
        elif "lora" in method_str or "peft" in method_str:
            return "medium (1-4 hours)"
        else:
            return "low (<1 hour)"
    
    def _get_input_requirements(self, domain: str) -> list[str]:
        """Get input requirements based on domain."""
        if "text" in domain or "language" in domain:
            return ["Text dataset (e.g., GLUE, SQuAD)", "Pretrained model weights"]
        elif "vision" in domain:
            return ["Image dataset (e.g., CIFAR-10, ImageNet subset)", "Pretrained vision model"]
        else:
            return ["Task-specific dataset", "Model configuration"]
    
    def get_statistics(self) -> dict:
        """Get executor statistics."""
        return {
            "codes_generated": self._generation_count,
            "output_dir": self.config.output_dir,
            "timeout": self.config.timeout_seconds
        }


if __name__ == "__main__":
    # Test the executor
    logging.basicConfig(level=logging.INFO)
    
    print("=" * 60)
    print("Testing CodeExecutor")
    print("=" * 60)
    
    executor = CodeExecutor()
    
    test_hypothesis = "LoRA rank adaptation during training improves convergence speed vs fixed rank"
    test_method = [
        "Compare fixed-rank LoRA vs adaptive-rank on GLUE tasks",
        "Start with low rank, increase based on gradient magnitude",
        "Measure convergence speed and final accuracy"
    ]
    
    generated = executor.generate_code(
        hypothesis=test_hypothesis,
        method_summary=test_method,
        domain="efficient fine-tuning"
    )
    
    print(f"\nGenerated Code Preview (first 50 lines):")
    print("-" * 60)
    for i, line in enumerate(generated.code.split('\n')[:50], 1):
        print(f"{i:3}: {line}")
    print("...")
    
    print(f"\nMetadata:")
    print(f"  Dependencies: {', '.join(generated.dependencies)}")
    print(f"  Estimated Runtime: {generated.estimated_runtime}")
    print(f"  Input Requirements: {', '.join(generated.input_requirements)}")
    print(f"  Output Files: {', '.join(generated.output_files)}")
    
    # Validate safety
    is_safe, issues = executor.validate_safety(generated.code)
    print(f"\nSafety Check: {'✓ Passed' if is_safe else '✗ Failed'}")
    if issues:
        for issue in issues:
            print(f"  - {issue}")
    
    # Save to file
    output_path = Path(executor.config.output_dir) / "test_experiment.py"
    generated.save(output_path)
    print(f"\nSaved to: {output_path}")
    
    print(f"\nStatistics: {executor.get_statistics()}")
