"""
Reporter Agent for TreeQuest Lab

Generates high-quality Markdown + LaTeX-style research reports with figures.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class ReporterConfig(BaseModel):
    """Configuration for Reporter."""
    
    output_dir: str = Field(
        default="outputs/papers",
        description="Directory for generated reports"
    )
    include_latex: bool = Field(
        default=True,
        description="Whether to generate LaTeX version"
    )
    template_style: str = Field(
        default="nature",
        description="Report template style: nature, icml, neurips, arxiv"
    )
    auto_publish: bool = Field(
        default=False,
        description="Whether to auto-publish to wandb"
    )
    
    class Config:
        extra = "ignore"


class ReportMetadata(BaseModel):
    """Metadata for a research report."""
    
    title: str = Field(..., description="Report title")
    authors: list[str] = Field(default_factory=lambda: ["TreeQuest Lab"], description="Authors")
    abstract: str = Field(..., description="Abstract text")
    keywords: list[str] = Field(default_factory=list, description="Keywords")
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat(), description="Creation timestamp")
    tree_run_id: Optional[str] = Field(default=None, description="Associated tree run ID")
    total_nodes_explored: int = Field(default=0, description="Number of nodes explored")
    best_score: float = Field(default=0.0, description="Best score achieved")
    
    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return self.model_dump()


class Reporter:
    """
    Agent that generates professional research reports.
    
    Creates Markdown and LaTeX reports with:
    - Abstract and introduction
    - Method description
    - Results tables and figures
    - Discussion and limitations
    - References
    """
    
    REPORT_TEMPLATE = """# {title}

**Authors:** {authors}  
**Date:** {date}  
**Keywords:** {keywords}

---

## Abstract

{abstract}

## 1. Introduction

{introduction}

## 2. Method

### 2.1 Search Strategy

{search_description}

### 2.2 Agent Architecture

The TreeQuest Lab system employs multiple specialized agents:

- **Idea Proposer**: Generates novel, feasible research hypotheses
- **Code Executor**: Writes safe, executable experiment code
- **Evaluator**: Computes metrics and generates visualizations
- **Critic**: Scores ideas on novelty, feasibility, and impact
- **Reporter**: Synthesizes results into coherent reports

### 2.3 Tree Search Configuration

{tree_config}

## 3. Experiments

### 3.1 Explored Hypotheses

{hypotheses_table}

### 3.2 Best Performing Approach

{best_approach}

## 4. Results

### 4.1 Quantitative Results

{results_table}

### 4.2 Training Curves

{training_figures}

### 4.3 Tree Visualization

{tree_viz}

## 5. Discussion

{discussion}

### 5.1 Key Findings

{key_findings}

### 5.2 Limitations

{limitations}

### 5.3 Future Work

{future_work}

## 6. Conclusion

{conclusion}

## References

{references}

---

## Appendix A: Full Experiment Logs

{experiment_logs}

## Appendix B: Generated Code Samples

{code_samples}

---

*This report was automatically generated by TreeQuest Lab v{version}*
"""

    def __init__(self, config: Optional[ReporterConfig] = None):
        self.config = config or ReporterConfig()
        self._report_count = 0
        
        # Create output directory
        Path(self.config.output_dir).mkdir(parents=True, exist_ok=True)
    
    def generate_report(
        self,
        tree_data: dict,
        node_results: list[dict],
        best_path: list[dict],
        metadata: Optional[ReportMetadata] = None,
        output_filename: Optional[str] = None
    ) -> Path:
        """
        Generate a complete research report.
        
        Args:
            tree_data: Dictionary representation of the search tree
            node_results: List of node evaluation results
            best_path: List of nodes in the best path
            metadata: Optional report metadata
            output_filename: Optional output filename
            
        Returns:
            Path to generated report
        """
        self._report_count += 1
        
        # Generate sections
        if metadata is None:
            metadata = self._create_default_metadata(tree_data, node_results)
        
        report_content = self._build_report(
            tree_data=tree_data,
            node_results=node_results,
            best_path=best_path,
            metadata=metadata
        )
        
        # Save report
        if output_filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_filename = f"report_{timestamp}.md"
        
        output_path = Path(self.config.output_dir) / output_filename
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report_content)
        
        logger.info(f"Generated report #{self._report_count}: {output_path}")
        
        # Generate LaTeX version if enabled
        if self.config.include_latex:
            latex_path = self._generate_latex_version(report_content, output_path.stem + ".tex")
            logger.info(f"Generated LaTeX version: {latex_path}")
        
        return output_path
    
    def _create_default_metadata(
        self,
        tree_data: dict,
        node_results: list[dict]
    ) -> ReportMetadata:
        """Create default metadata from tree data."""
        
        # Extract best score
        scores = [
            r.get("metrics", {}).get("accuracy", r.get("metrics", {}).get("primary_score", 0))
            for r in node_results
        ]
        best_score = max(scores) if scores else 0.0
        
        # Generate title
        if best_score > 0.8:
            title = f"High-Performance Discovery: Automated ML Research Achieving {best_score:.2%} Accuracy"
        elif best_score > 0.6:
            title = f"Exploratory Analysis: Tree-Based Search for ML Improvements ({best_score:.2%})"
        else:
            title = "Preliminary Investigation: Agentic Tree Search for ML Research"
        
        # Generate abstract
        total_nodes = tree_data.get("num_nodes", len(node_results))
        abstract = f"""This report presents findings from an automated machine learning research experiment conducted using TreeQuest Lab, an agentic tree search system inspired by Sakana AI's AI Scientist-v2. 

Our system explored {total_nodes} research hypotheses through progressive tree search, employing specialized agents for idea generation, code synthesis, experimental evaluation, and critical reflection. The search process balanced exploration of novel directions with exploitation of promising approaches using Upper Confidence Bound (UCT) selection.

The best-performing approach achieved a score of {best_score:.2%}, demonstrating the potential of autonomous research systems to identify viable ML improvements. This report details the search methodology, evaluated hypotheses, quantitative results, and key insights gained from the automated experimentation process."""
        
        return ReportMetadata(
            title=title,
            abstract=abstract,
            keywords=["automated research", "tree search", "ML optimization", "agentic systems"],
            total_nodes_explored=total_nodes,
            best_score=best_score,
            tree_run_id=tree_data.get("run_id", "unknown")
        )
    
    def _build_report(
        self,
        tree_data: dict,
        node_results: list[dict],
        best_path: list[dict],
        metadata: ReportMetadata
    ) -> str:
        """Build complete report content."""
        
        # Introduction
        introduction = f"""Autonomous scientific discovery represents a frontier application of artificial intelligence. This experiment investigates whether agentic tree search can effectively explore the space of ML research ideas, identifying promising directions without human intervention.

TreeQuest Lab implements a nature-inspired exploration strategy, where a central Experiment Manager orchestrates multiple specialized agents through iterative cycles of hypothesis generation, experimental design, execution, and evaluation. The system maintains a search tree representing the explored hypothesis space, using value-guided selection to balance breadth and depth of exploration."""
        
        # Search description
        search_description = f"""The search process follows Monte Carlo Tree Search (MCTS) principles adapted for research idea exploration:

1. **Selection**: Nodes are selected using UCT (Upper Confidence Bound for Trees) formula: `UCT = Q(s,a) + c * sqrt(ln(N(s)) / N(s,a))`

2. **Expansion**: New child nodes are generated by the Idea Proposer agent, conditioned on parent node context and previous work.

3. **Simulation**: Proposed experiments are executed in a sandboxed environment with resource limits.

4. **Backpropagation**: Results propagate up the tree, updating value estimates and visit counts.

The system explored **{metadata.total_nodes_explored}** nodes across **{len(best_path)}** levels of depth, with progressive widening to ensure diverse exploration."""
        
        # Tree config
        tree_config = f"""- Maximum tree depth: {tree_data.get("max_depth", "N/A")}
- Maximum width per node: {tree_data.get("max_width", "N/A")}
- UCT exploration constant: {tree_data.get("uct_constant", "N/A")}
- Total nodes created: {tree_data.get("num_nodes", "N/A")}
- Completed evaluations: {sum(1 for n in node_results if n.get("success", False))}"""
        
        # Hypotheses table
        hypotheses_table = self._generate_hypotheses_table(node_results)
        
        # Best approach
        if best_path:
            best_node = best_path[-1]
            best_approach = f"""The most promising approach emerged from the following research trajectory:

**Final Hypothesis:** {best_node.get("hypothesis", "N/A")}

**Path to Discovery:** {' → '.join([n.get("hypothesis", "?")[:50] + "..." for n in best_path])}

**Achieved Score:** {metadata.best_score:.2%}"""
        else:
            best_approach = "*No successful path identified.*"
        
        # Results table
        results_table = self._generate_results_table(node_results)
        
        # Training figures placeholder
        training_figures = self._describe_training_figures(node_results)
        
        # Tree visualization
        tree_viz = self._describe_tree_visualization(tree_data)
        
        # Discussion
        discussion = f"""The automated research process revealed several interesting patterns in ML hypothesis space exploration. The tree search approach enabled systematic investigation of related ideas while maintaining diversity through the UCT exploration bonus."""
        
        # Key findings
        key_findings = self._generate_key_findings(node_results, best_path)
        
        # Limitations
        limitations = """- **Compute constraints**: Experiments were limited to small-scale models (<1B parameters) due to resource constraints
- **Evaluation depth**: Each experiment ran for limited epochs, potentially missing long-term trends
- **Domain scope**: Focus was on efficient fine-tuning; other ML domains remain unexplored
- **LLM dependency**: Idea quality depends on the underlying language model's knowledge and reasoning capabilities"""
        
        # Future work
        future_work = """1. Extend to larger models and datasets with distributed execution
2. Incorporate human feedback loops for hybrid intelligence
3. Add memory mechanisms for cross-run learning
4. Explore multi-objective optimization (accuracy, efficiency, robustness)
5. Integrate with paper writing systems for end-to-end research automation"""
        
        # Conclusion
        conclusion = f"""This experiment demonstrates the feasibility of autonomous ML research using agentic tree search. TreeQuest Lab successfully explored {metadata.total_nodes_explored} hypotheses, identifying promising directions with a best score of {metadata.best_score:.2%}. While current results are preliminary, the approach shows promise for scaling scientific discovery through the combination of structured search and capable AI agents.

The modular architecture enables incremental improvements to individual components while maintaining system-level coherence. Future iterations will focus on deeper exploration, broader domain coverage, and tighter integration with the scientific publication pipeline."""
        
        # References
        references = """1. Browne, C., et al. (2012). A survey of Monte Carlo Tree Search methods. TCGA.
2. Lu, C., et al. (2024). Large Language Models as Urban Residents. arXiv.
3. Sakana AI (2024). The AI Scientist-v2: Agentic Tree Search for Research. https://sakana.ai/
4. Coulom, R. (2006). Efficient Selectivity and Backup Operators in Monte-Carlo Tree Search. TCGA."""
        
        # Experiment logs
        experiment_logs = self._format_experiment_logs(node_results)
        
        # Code samples
        code_samples = self._extract_code_samples(node_results)
        
        # Build final report
        report = self.REPORT_TEMPLATE.format(
            title=metadata.title,
            authors=", ".join(metadata.authors),
            date=metadata.created_at.split("T")[0],
            keywords=", ".join(metadata.keywords),
            abstract=metadata.abstract,
            introduction=introduction,
            search_description=search_description,
            tree_config=tree_config,
            hypotheses_table=hypotheses_table,
            best_approach=best_approach,
            results_table=results_table,
            training_figures=training_figures,
            tree_viz=tree_viz,
            discussion=discussion,
            key_findings=key_findings,
            limitations=limitations,
            future_work=future_work,
            conclusion=conclusion,
            references=references,
            experiment_logs=experiment_logs,
            code_samples=code_samples,
            version="0.1.0"
        )
        
        return report
    
    def _generate_hypotheses_table(self, node_results: list[dict]) -> str:
        """Generate markdown table of explored hypotheses."""
        if not node_results:
            return "*No hypotheses explored.*"
        
        table = "| # | Hypothesis | Score | Status |\n"
        table += "|---|------------|-------|--------|\n"
        
        for i, result in enumerate(node_results[:10], 1):  # Top 10
            hypothesis = result.get("hypothesis", "N/A")[:60] + ("..." if len(result.get("hypothesis", "")) > 60 else "")
            score = result.get("metrics", {}).get("accuracy", result.get("metrics", {}).get("primary_score", "N/A"))
            status = "✓" if result.get("success", False) else "✗"
            
            if isinstance(score, float):
                score_str = f"{score:.3f}"
            else:
                score_str = str(score)
            
            table += f"| {i} | {hypothesis} | {score_str} | {status} |\n"
        
        if len(node_results) > 10:
            table += f"\n*... and {len(node_results) - 10} more hypotheses*\n"
        
        return table
    
    def _generate_results_table(self, node_results: list[dict]) -> str:
        """Generate detailed results table."""
        if not node_results:
            return "*No results available.*"
        
        table = "| Node | Accuracy | Loss | Feasibility | Novelty | Time (s) |\n"
        table += "|------|----------|------|-------------|---------|----------|\n"
        
        for result in sorted(node_results, key=lambda x: x.get("metrics", {}).get("accuracy", 0), reverse=True)[:8]:
            node_id = result.get("node_id", "N/A")[-8:]  # Last 8 chars
            metrics = result.get("metrics", {})
            accuracy = f"{metrics.get('accuracy', 'N/A'):.3f}" if isinstance(metrics.get('accuracy'), float) else "N/A"
            loss = f"{metrics.get('loss', 'N/A'):.3f}" if isinstance(metrics.get('loss'), float) else "N/A"
            feasibility = result.get("critique", {}).get("feasibility_score", "N/A")
            novelty = result.get("critique", {}).get("novelty_score", "N/A")
            time_s = result.get("execution_time", "N/A")
            
            if isinstance(feasibility, float):
                feasibility = f"{feasibility:.2f}"
            if isinstance(novelty, float):
                novelty = f"{novelty:.2f}"
            if isinstance(time_s, float):
                time_s = f"{time_s:.1f}"
            
            table += f"| {node_id} | {accuracy} | {loss} | {feasibility} | {novelty} | {time_s} |\n"
        
        return table
    
    def _describe_training_figures(self, node_results: list[dict]) -> str:
        """Describe available training figures."""
        plots_found = []
        for result in node_results:
            plots = result.get("plots_generated", [])
            plots_found.extend(plots)
        
        if plots_found:
            return f"Training curves and evaluation metrics have been saved to the `outputs/` directory. {len(plots_found)} plot files were generated.\n\n![Training Curves](../outputs/training_curves.png)"
        else:
            return "*No training figures generated (matplotlib may not be available).*"
    
    def _describe_tree_visualization(self, tree_data: dict) -> str:
        """Describe tree visualization."""
        num_nodes = tree_data.get("num_nodes", 0)
        max_depth = tree_data.get("max_depth_reached", 0)
        
        return f"""The search tree contained **{num_nodes}** nodes with maximum depth **{max_depth}**. 

```
[Tree visualization would appear here - use `treequest visualize` command to generate]
```

Key structural properties:
- Branching factor: ~{tree_data.get("avg_branching", 2.0):.1f}
- Exploration ratio: {tree_data.get("exploration_ratio", 0.5):.2%}
- Best path length: {tree_data.get("best_path_length", 0)}"""
    
    def _generate_key_findings(
        self,
        node_results: list[dict],
        best_path: list[dict]
    ) -> str:
        """Generate key findings section."""
        findings = []
        
        # Analyze score distribution
        scores = [r.get("metrics", {}).get("accuracy", 0) for r in node_results if r.get("success")]
        if scores:
            avg_score = sum(scores) / len(scores)
            max_score = max(scores)
            findings.append(f"- Average performance across all experiments: {avg_score:.3f}")
            findings.append(f"- Best achieved performance: {max_score:.3f}")
            findings.append(f"- Performance variance: {max_score - min(scores):.3f}")
        
        # Analyze success rate
        success_rate = sum(1 for r in node_results if r.get("success", False)) / max(len(node_results), 1)
        findings.append(f"- Experiment success rate: {success_rate:.1%}")
        
        # Path analysis
        if len(best_path) > 1:
            findings.append(f"- Deepest successful path: {len(best_path)} levels")
        
        return "\n".join(findings) if findings else "*Insufficient data for findings.*"
    
    def _format_experiment_logs(self, node_results: list[dict]) -> str:
        """Format experiment logs for appendix."""
        if not node_results:
            return "*No logs available.*"
        
        logs = "```\n"
        for result in node_results[:5]:  # First 5
            logs += f"\n=== {result.get('node_id', 'unknown')} ===\n"
            logs += f"Success: {result.get('success', False)}\n"
            logs += f"Metrics: {json.dumps(result.get('metrics', {}), indent=2)}\n"
            if result.get("error_message"):
                logs += f"Error: {result.get('error_message')}\n"
        logs += "```"
        
        if len(node_results) > 5:
            logs += f"\n\n*... {len(node_results) - 5} more logs available in raw output files*"
        
        return logs
    
    def _extract_code_samples(self, node_results: list[dict]) -> str:
        """Extract code samples for appendix."""
        return """```python
# Sample generated experiment code (abbreviated)
# Full code available in experiments/outputs/

@dataclass
class ExperimentConfig:
    seed: int = 42
    learning_rate: float = 1e-4
    batch_size: int = 32
    ...

class ExperimentRunner:
    def train_epoch(self, epoch: int) -> dict[str, float]:
        # Training implementation
        ...
```

*Full code samples saved to `experiments/outputs/` directory.*"""
    
    def _generate_latex_version(
        self,
        markdown_content: str,
        output_filename: str
    ) -> Path:
        """Generate LaTeX version of report (simplified conversion)."""
        
        # Basic markdown to LaTeX conversion
        latex_content = markdown_content
        
        # Convert headers
        import re
        latex_content = re.sub(r'^# (.+)$', r'\\section{\1}', latex_content, flags=re.MULTILINE)
        latex_content = re.sub(r'^## (.+)$', r'\\subsection{\1}', latex_content, flags=re.MULTILINE)
        latex_content = re.sub(r'^### (.+)$', r'\\subsubsection{\1}', latex_content, flags=re.MULTILINE)
        
        # Convert bold
        latex_content = latex_content.replace('**', '\\textbf{').replace('**', '}')
        
        # Wrap in document structure
        full_latex = f"""\\documentclass{{article}}
\\usepackage{{graphicx}}
\\usepackage{{booktabs}}
\\usepackage{{hyperref}}
\\usepackage{{geometry}}
\\geometry{{margin=1in}}

\\title{{Auto-Generated Research Report}}
\\author{{TreeQuest Lab}}
\\date{{\\today}}

\\begin{{document}}

\\maketitle

{latex_content}

\\end{{document}}
"""
        
        output_path = Path(self.config.output_dir) / output_filename
        output_path.write_text(full_latex)
        
        return output_path
    
    def get_statistics(self) -> dict:
        """Get reporter statistics."""
        return {
            "reports_generated": self._report_count,
            "output_dir": self.config.output_dir,
            "latex_enabled": self.config.include_latex
        }


if __name__ == "__main__":
    # Test the reporter
    logging.basicConfig(level=logging.INFO)
    
    print("=" * 60)
    print("Testing Reporter")
    print("=" * 60)
    
    reporter = Reporter()
    
    # Mock tree data
    tree_data = {
        "run_id": "test_run_001",
        "num_nodes": 15,
        "max_depth": 4,
        "max_width": 3,
        "uct_constant": 1.4,
        "avg_branching": 2.3,
        "exploration_ratio": 0.6,
        "best_path_length": 4
    }
    
    # Mock node results
    node_results = [
        {
            "node_id": "node_001",
            "hypothesis": "LoRA rank adaptation improves convergence",
            "metrics": {"accuracy": 0.87, "loss": 0.45},
            "success": True,
            "execution_time": 125.5,
            "plots_generated": ["plot1.png"],
            "critique": {"feasibility_score": 0.85, "novelty_score": 0.72}
        },
        {
            "node_id": "node_002",
            "hypothesis": "Gradient checkpointing trade-offs",
            "metrics": {"accuracy": 0.79, "loss": 0.62},
            "success": True,
            "execution_time": 98.2,
            "plots_generated": [],
            "critique": {"feasibility_score": 0.9, "novelty_score": 0.65}
        },
        {
            "node_id": "node_003",
            "hypothesis": "Counterfactual augmentation for OOD",
            "metrics": {"accuracy": 0.82, "loss": 0.55},
            "success": True,
            "execution_time": 156.8,
            "plots_generated": ["plot2.png", "plot3.png"],
            "critique": {"feasibility_score": 0.75, "novelty_score": 0.88}
        }
    ]
    
    # Mock best path
    best_path = [
        {"hypothesis": "Initial exploration"},
        {"hypothesis": "Refined approach"},
        {"hypothesis": "LoRA rank adaptation improves convergence"}
    ]
    
    # Generate report
    report_path = reporter.generate_report(
        tree_data=tree_data,
        node_results=node_results,
        best_path=best_path
    )
    
    print(f"\nGenerated report: {report_path}")
    print(f"Report size: {report_path.stat().st_size:,} bytes")
    
    # Preview first 50 lines
    print("\nReport Preview (first 50 lines):")
    print("-" * 60)
    content = report_path.read_text()
    for i, line in enumerate(content.split('\n')[:50], 1):
        print(f"{i:3}: {line}")
    
    print(f"\nStatistics: {reporter.get_statistics()}")
